config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"

  resources :sessions, only: [:new, :create]

  resources :movies
  resources :showings do
    resources :sales
  end
  resources :theaters do
    resources :auditoria
  end

  delete "/logout" => "sessions#destroy"
  get "/saleshistory" => "sales#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  has_secure_password
  validates :username, presence: :true

end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base

  belongs_to :theater
  has_many :showings

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :showings

end

app/models/sale.rb
class Sale < ActiveRecord::Base

  belongs_to :showing

end

app/models/showing.rb
class Showing < ActiveRecord::Base

  belongs_to :auditorium
  belongs_to :movie
  has_many :sales

  def available_seating
    self.auditorium.seating_capacity - self.sales.count
  end

end

app/models/theater.rb
class Theater < ActiveRecord::Base

   has_many :auditoria

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper Sessionable
  include Sessionable
end

app/controllers/auditoria_controller.rb
class AuditoriaController < ApplicationController
  before_action :find_auditorium, only: [:edit, :update, :destroy]

  def new
    @theater = Theater.find(params[:theater_id])
    @auditorium = Auditorium.new
  end

  def create
    @auditorium = Auditorium.new(auditorium_params)
    @theater = Theater.find(params[:theater_id])
    if @auditorium.save
      redirect_to theater_path(@theater)
    else
      render 'new'
    end
  end

  def edit
    @theater = Theater.find(params[:theater_id])
  end

  def update
    if @auditorium.update_attributes(auditorium_params)
      redirect_to @auditorium.theater
    else
      render 'edit'
    end
  end

  def destroy
    if @auditorium.destroy
      redirect_to root_path
    end
  end

  private

  def auditorium_params
    params.require(:auditorium).permit(:auditorium_number, :seating_capacity, :theater_id)
  end

  def find_auditorium
    @auditorium = Auditorium.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:edit, :update, :show, :destroy]
  def index
    @movies = Movie.where(playing: true)
  end

  def show

  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @movie.update_attributes(movie_params)
      redirect_to @movie
    else
      render 'edit'
    end
  end

  def destroy

    if @movie.destroy
      redirect_to root_path
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :playing)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :find_sale, only: [:edit, :update, :show, :destroy]

  def index
    @sales = Sale.all
  end

  def show
  end

  def new
    @sale = Sale.new
  end

  def create
    @showing = Showing.find([params[:showing_id]])
    @sale = Sale.new(sale_params)
    respond_to do|format|
      if @sale.save
        SalesMailer.confirmation_email(@sale).deliver_now
        format.html { redirect_to showing_path(@showing), notice: 'You just bought a ticket!' }
        format.json {render json: @sale, status: :created, location: @sale}
      else
        format.html {redirect_to showing_path(@showing), notice: "Your order could not be processed, please try again"}
        format.json {render json: @sale.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    if @sale.update_attributes(sale_params)
      redirect_to @sale
    else
      render 'edit'
    end
  end

  private

  def sale_params
    params.require(:sale).permit(:customer_name, :customer_email, :showing_id)
  end

  def find_sale
    @sale = Sale.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.find_by(username: params[:sessions][:username])
    if @admin && @admin.authenticate(params[:sessions][:password])
        session[:admin_id] = @admin.id
        redirect_to root_path
    else
      @errors = ["Invalid login info"]
      render :new
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to root_path
  end
end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
  before_action :find_showing, only: [:edit, :update,:show, :destroy]
  def show
    @sale = Sale.new
  end

  def new
    @showing = Showing.new
  end

  def create
    @movie = Movie.find(params[:showing][:movie_id])
    @showing = Showing.new(showing_params)
    if @showing.save
      redirect_to movie_path(@movie)
    else
      render 'new'
    end
  end

  def update
    if @showing.update_attributes(theater_params)
      redirect_to @showing
    else
      render 'edit'
    end
  end

  def destroy
    if @showing.destroy
      redirect_to root_path
    end
  end

  private

  def showing_params
    params.require(:showing).permit(:time, :movie_id, :auditorium_id)
  end

  def find_showing
    @showing = Showing.find(params[:id])
  end
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  before_action :find_theater, only: [:edit, :update,:show, :destroy]

  def index
    @theaters = Theater.all
  end

  def show
  end

  def new
    @theater = Theater.new
  end

  def create
    @theater = Theater.new(theater_params)
    if @theater.save
      redirect_to @theater
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @theater.update_attributes(theater_params)
      redirect_to @theater
    else
      render 'edit'
    end
  end

  def destroy
    if @theater.destroy
      redirect_to root_path
    end
  end

  private

  def theater_params
    params.require(:theater).permit(:name)
  end

  def find_theater
    @theater = Theater.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auditirua_helper.rb
module AuditiruaHelper
end

app/helpers/auditoria_helper.rb
module AuditoriaHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessionable.rb
module Sessionable
  def logged_in?
    session[:admin_id] != nil
  end

  def current_user
    @current_user ||= Admin.find(session[:admin_id]) if logged_in?
  end
end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/application/_errors.html.erb
<% if thing.errors.any? %>
<div = id="error_explanation">
  <h2>
    <%= pluralize(thing.errors.count, 'error') %>
  </h2>
  <ul>
    <% thing.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end  %>
  </ul>
</div>
<% end %>

app/views/auditoria/_form.html.erb
<%= form_for [@theater, @auditorium] do |f| %>

  <%= render 'errors', :thing => @auditorium %>
  <p>
    <%= f.label :auditorium_number %><br>
    <%= f.text_field :auditorium_number %>
  </p>
  <p>
    <%= f.label :seating_capacity %><br>
    <%= f.text_field :seating_capacity %>
  </p>
  <%= f.hidden_field :theater_id, :value => @theater.id %>
  <p>
    <%= f.submit %>
  </p>
 <% end %>

app/views/auditoria/edit.html.erb
<h2>Update Auditorium</h2>

<%= render 'form' %>

app/views/auditoria/new.html.erb
<h2>Add an auditorium to <%= @theater.name %></h2>
<%= render 'form' %>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>

  <%= render 'errors', :thing => @movie %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.hidden_field :playing, :value => true %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 <% end %>

app/views/movies/_movie.html.erb
<li>
  <%= link_to "#{movie.title}", movie_path(movie)%>
  <ul>
    <% movie.showings.each do |showing|%>
      <li>
        <%= link_to "#{showing.time}", showing_path(showing)%>
      </li>
    <% end %>
  </ul>
</li><br>

app/views/movies/edit.html.erb
<h2>Edit Movie</h2>

<%= render 'form' %>

app/views/movies/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <ul>
      <%= render @movies || "There are currently no movies playing =[" %>
    </ul>
  </div>
</div>
<div>
  <% if logged_in? %>
    <%= link_to "Add Movies", new_movie_path %>
    <%= link_to "Add Showings", new_showing_path %>
  <% end %>
</div>

app/views/movies/new.html.erb
<h2>Add a movie to the theater</h2>

<%= render 'form' %>

app/views/movies/show.html.erb
<h1> <%= @movie.title %> </h1>
<% if logged_in? %>
  <%= link_to "Edit Movie", edit_movie_path(@movie) %>
  <%= link_to "Delete movie", movie_path(@movie), method: :delete %>
<% end %>
<ul>
  <% @movie.showings.each do |showing| %>
    <li>
      <%= link_to "#{showing.time}", showing_path(showing) %>
    </li>
    <% end %>
</ul>

app/views/sales/_form.html.erb
<%= form_for [@showing, @sale] do |f| %>
  <%= render 'errors', :thing => @sale %>
  <p>
    <%= f.label :customer_name%>
    <%= f.text_field :customer_name%>
  </p>
  <p>
    <%= f.label :customer_email%>
    <%= f.text_field :customer_email%>
  </p>
    <%= f.hidden_field :showing_id, :value => @showing.id %>
  <p>
    <%= f.submit%>
  </p>
<% end %>

app/views/sales/_sale.html.erb
<div class="block">
  <ul>
    <li>
      <%= sale.id %>
    </li>
    <li>
      <%= sale.showing.movie.title %>
    </li>
    <li>
      <%= sale.customer_name %>
    </li>
    <li>
      <%= sale.customer_email %>
    </li>
  </ul>
</div> <br>

app/views/sales/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <ul>
      <%= render @sales || "There are currently no sales" %>
    </ul>
  </div>
</div>

app/views/showings/_form.html.erb
<%= form_for @showing do |f| %>

  <%= render 'errors', :thing => @showing %>
  <p>
    <%= f.label :time %><br>
    <%= f.datetime_select :time, :ampm => true %>
  </p>
    <p>
    <%= f.label :movie_id %><br>
    <%= f.collection_select :movie_id, Movie.where(playing: true), :id, :title,include_blank: true %>
  </p>
  <p>
    <%= f.label :auditorium_id %><br>
    <%= f.collection_select :auditorium_id, Auditorium.all, :id, :auditorium_number, include_blank: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
 <% end %>

app/views/showings/new.html.erb
<h2>Add a showtime for the movie</h2>

<%= render 'form' %>

app/views/showings/show.html.erb
<h1> <%= @showing.movie.title %> </h1>

<h3> Auditorium <%= @showing.auditorium.auditorium_number %> @ <%= @showing.time %> </h3>
<% if logged_in? %>
  <%= link_to "Edit Showing", edit_showing_path(@showing) %>
  <%= link_to "Delete Showing", showing_path(@showing), method: :delete%>
<% end %>
<%= render "/sales/form" %>

app/views/theaters/_form.html.erb
<%= form_for @theater do |f| %>

  <%= render 'errors', :thing => @theater %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
 <% end %>

app/views/theaters/_theater.html.erb
<li>
  <%= link_to "#{theater.name}", theater_path(theater)%>
  <ul>
    <% theater.auditoria.each do |auditorium|%>
      <li>
        <%= "Auditorium #{auditorium.auditorium_number}"%>
      </li>
      <ul>
        <li>
          <%= "Capacity: #{auditorium.seating_capacity}"%>
        </li>
      </ul>
    <% end %>
  </ul>

</li>

app/views/theaters/edit.html.erb
<h2>Update Theater Name</h2>

<%= render 'form' %>

app/views/theaters/index.html.erb
<div>
  <ul>
    <%= render @theaters || "There are currently no theaters available =[" %>
  </ul>
</div>

<div>
  <% if logged_in?%>
    <%= link_to "Add Theater", new_theater_path %>
  <% end %>
</div>

app/views/theaters/new.html.erb
<h2>Add a theater to the company</h2>
<%= render 'form' %>

app/views/theaters/show.html.erb
<h1> <%= "#{@theater.name}" %> </h1>
  <% if logged_in? %>
    <%= link_to "Edit Theater Name", edit_theater_path(@theater) %>
    <%= link_to "Delete Theater", theater_path(@theater), method: :delete %>
  <% end %>
<ul>
    <% @theater.auditoria.each do |auditorium|%>
      <li>
        <%= "Auditorium #{auditorium.auditorium_number}"%>
      </li>
      <ul>
        <li>
          <%= "Capacity: #{auditorium.seating_capacity}"%>
        </li>
      </ul>
      <% if logged_in? %>
        <%= link_to "Edit Auditorium", edit_theater_auditorium_path(@theater,auditorium) %>
        <%= link_to "Delete Theater", theater_auditorium_path(@theater,auditorium), method: :delete %>
      <% end %>
    <% end %>
  </ul>

<div>
  <% if logged_in? %>
    <%= link_to "Add Auditorium", new_theater_auditorium_path(@theater) %>
  <% end %>
</div>